name: Vizio TV Remote Card
description: Vizio TV Remote Card for Home Assistant Lovelace UI
type: lovelace
keywords:
  - tv
  - remote
  - media
  - vizio
  - screen
author:
  name: jdmar3
license: GNU General Public License v3.0 or later
files:
  - vizio-card.js
  - vizio-card-editor.js
